from turtle import *
cal = ["CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJCCCCJJJJCCJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJJJCJJJJCCCCJJCCJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJCUCL0O0LJCL0LJJJJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJCL0Qc/}_llli[v0UJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJCQQv{i:,::;II;:"(0JCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJCCJJCOC/~::;Il!!llIIlI,jQJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJCCCCJCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJJJOJ)I,;Il!llI;::I!Il;iQCJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJCCU0L|I:;llIII;,:~?[l;llI:YCJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJJCJJCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJULOr!";IlI;l!:I(cQOOQ_IlI,vLJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJUJJJJCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJOY-,I!I;lll;;|C0CJUY0r:Il,cLJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJQ0LQ0CCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJCCCCCJULO/;:IIllIIl,+XOLJCCJU0r,ll;YCJCCCCCCCCCCCCCCCCCCCCCCCCCCCJJCJUQLj?!!|QJCJCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJC0J-,lI;IIlII:)0LYUCJJLJQ|;l;iLCJCCCCCCCCCCCCCCCCCCCCCCCCCCCJJCC0xi":I;"QQJJCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJOuI;!IlllIII,jOJCCJCCJUCL!Il:)QJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJQU?";lIIlI~QJCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJCO|"IlIIlI;I;IvOJCJCJCJJQO]:Il:XLJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCOx;:llIIIl;ICCJCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJCJL0[,lIlIIIIl;:c0YCLJJL00Qz_:lI:}QCCJCCCCCCCCCCCCCCCCCCCCCCCCCJCO|"IIlIIIIlIlJJJCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJCCJJQL+,lIIIIIlII;z0JCUCC0z|[~":llI;CJCCCCCCCCCCCCCCCCCCCCCJJCCCJUL0[,IIIIIIIll;iCJCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJUJCCULLi:!IIIIlIII;c0UJCCJC{:,:;lI;!^j0JCJCCCCCCCCCCCCCCCCCCCCCCCCUU0],lll;I;IlII:?0UJCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJYLJl;lIIIIIl;l,n0JCJJC0],!lIIIIi:{OJCJJCCCCCCCCCCCCCCCCCCCCCCCJC0+"lIlIl;IL[;!:QOJJCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCU0YI;l;IIIIIIl"fOJJJLJCz,l;IIII!:?OJLJJCCCCCCCCCCCCCCCCCCCCCCCJC0?"lII;l;lLOIIl:v0CJCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCUQCI;IIlIIIII!:1ZJCJLJJLx,lIlIIl"?0JJJJCCJCCCCCCCCCCCCCCCCCCCJCJO[:lIII;!;XZx"I;iQCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJULC!:lIIII;lIl;-OCJCCCCCJJ;Illl;"10CCCCCCCCCCCCCCCCCCCCCCCCCCJJJO(,!IIIlI,uQQ-;l,|0JCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJL~:lIIII;ll;;IJLJCCCCCJJ0j;,":ixZUJCCCCCCCCCCCCCCCCCCCCCCCCCJCOj,lIIIIl"|QJc:!l,XLJJCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCUZ?"lIIIIIIlIl:n0JJCCCCCCCJ0Uj/rL0JJCJJCCCCCCCCCCCCCCCCCCCCCCCUQX:lIIIIl,_OU0[:l;-QJJJCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJO),lllIIIIl;l:(ZUCJJCCCCJUJJCLOQJJJCCCCCCCCCCCCCCCCCCCCCCCCCCJCQ!IIIIIII;JCLz:ll"nQUCJCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJU0x"!IIIIIIIIlIiQCJJCCCCCCCCJJJUJJJJCCJJCCCCCCCCCCCCCCCCCCCCCJJJO{:lIIII!,f0YO]:iliQJJCJJCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJLU:IIIIIIIII;I,vQJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJCU0x"!IIIII;_ZULz"Il,jQJCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCJCJ0_:lIIIIIIIIl"{0JCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJUCCC!IIIII;I,zLJO-;lI!QCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCU0|,lIIIIIIIIIIlCCJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJUO1:IIl;Il,{OYQu,ll,f0JCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCJLz,lIIIIIIIIIl"j0UJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCLX:I;lI;l;:UCJO+;I;iQJCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCJJJCJ0+IIIIIIIIlIl;+OCUJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJO?;III;Il")0YOj,ll"rQJJCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCJ0f,IIIIIIIIII!"nLJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJQv"llIIIII:JLCCIII;~0JCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCJCCJQlI;lIIIIIIlI;_0YCJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJ0?:IlIIIl:}OUO);!l,uLJCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCJJUQ|,lll;IIII;lI"n0JCJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJLv,IIIIIIl:zLCz:!;:]0JLJCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCJUCC;;llIIIIIIII;~QJJJJJCCCCCCCCCCCCCCCCCCCCCCJJJJCCJJJJJJJJCCCCCJO[:ll;IIl;_QU0-:II:XLJJCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCJO|,IIIIIIIIIIl,j0JJJCCCCCCCCCCCCCCCCJCJJJJJLLQQQCUCQQQLLQQJJCJJLU:IlI;Ill"jQQj"I!,(OJCJCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCQ!;IIIIIIIIIIIICCCCCCCCCCCCCCCCCCCCJUCJJL0QUvrfnJOYfjjjfjjUCJCUQQ,llIIIIIIJLL;Il;lLCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCJQx:lIIIIIIIIIl:10UCCCCCCCCCCCCCCCCCCCJJCOY|_l"","Ir_"::,:",_0JCCL+IIIIII;;[Q0{,l!"xLJCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCU0?:lIIIIIIIIIl:cLJCCCCCCCCCCCCCCCCCCJCOX[:::IIlllI:;llIIIII;CJJQc,lIIIII;,fZx"lI:[OJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCU;IlIIIIIIIII:iQJCCCCCCCCCCCCCCCCCCJQQ)::llIII;:;IlI;IlIIl:[OUU0Q"IIIIIII:U0!IlI:CCJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCJQf"lIIIIIIIIIl")OUCCCCCCCCCCCCCCCCJJQz!"llIIl;"i]I:lIIIII;l,uQJJ0-:IIIIIl:~w[,li"j0UCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCJO[:lIIIIIIIIIl"nQUJCCCCCCCCCCCCCCJJZj,:llIII,In00Li;lIIIII;~0JJCJIIIIII;I:|c"II:-0ULJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCJLi;IIIIIIIIIIIIJCCCCCCCCCCCCCCCCCUO|"llllIl:+C0CJZ+:IIIIIl"fQJJQv,lIIIIIl:jiIll;ULCJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJLX,lI;IIIIIIIl;+QCCCCCCCCCCCCCCCCJO|"llIIIl:!LLJUQr"lIIIIIIILCJJ0t,lIIIIIlIiIIl"jQCCUJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJQn^!l;IIIIIIIl:}0CJJCCCCCCCCCJJCUOt"IllIlII:XLJJJO_;IlIIIl,(0JJJO}:lIIII;Il;ll,]OYJJJLJCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJ0Q"lIIIIIIIIIl"Q0JCJCCCCCCCCCJCJLv"lIIIIlI,fOUJJQv,l;IIlII;ULJJJ0-;lIIIIIllII;!QCJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJ01,lIIIIIIIIIl"rQJCJCCCCCCCCCCCCJIIIIIIII:+0JJCJO],llII;l:[OJJJJL~;IIIIIIII;I,vQJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJ0}:lIIIIIIIIII,nLJCCCCCCCCCCCJU0]:IIIIIlI:uLJCJCY:IIlIl;!,vLJJCCCi;IIIIII;I!"/OJJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJ0?:lIIIIIIIIII,uLJJCCCCCCCCCCUQr,l;IIIIl;?QCJJJ0),lII;lII_0UCJCCJl;lIIIII;l,?OCCJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJQ?:lIIIIIIIIII"uQJJCCCCCCJJJJCQl;lIIIIIl:nQJUUCCI;IIIIII,rQJLJCCJl;lIIIIII;!LCJUCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJ0]:lIIIIIIIIIl"xQYCCJCCCCCJJJOQ"lIIIIII;~QJCJU0t,lIIIlI:!QJCCCCJC!;IIIIIl;;ULJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJ01:lIIIIIIIIIl"fQYCCCCCCCCLJCLI;lIIIIIl,(0UJCJ0~;IIIIIl,)0JCCCCCCi;lIIIIl:+QJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJ0|,!IIIIIIIIIl,(0UCCCCCCCJCUQ/,lIIIIIIl:vLJJULu,lIIIIIl:XLJCCCCCQ~;lIIIIIIiJCJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJQx"lIIIIIIIIIl:]QJCJCCCCCJCJL!IIIlIIII;!LCJCU0[:lIIIIl;-0JCCCCCJQ}:lIIIIII;ULCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCJLY:IIIIIIIIIIlI!CCJJCCCJJJJ0t,lIIlIIIl;-0JUCCU;IIIIIII:rQUCCCCJUZ|:IIIIIlI"xLCCCCJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCJQ~;IIIIIIIIIIl:u0JJJJJCLUCC;IIIIIIIIl:?LJCYO(:lIIIII;lCCJJCCJCZQ,lIIIIIIl,)0JCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCJ0(:!IIIIIIIIIl:_OCJJCJCJCO-;lIIIIIIIl:?0UJ0u:lIIIIIl:[QJCJCUCO{,IIlIIIIIl;!0JJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCLU;llIIIIIIIIIl"QZJUJJUL0],lIIIIIIIIIIlYOZu;;;lIIIIl:QLJJUCOY+"IllIIIIII;I"x0UJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCJO(,lIIIIIIIIIlI,|QQQLQvi,lIIIIIIIIIIIII[?,Il;IIIIIl,tOCL0LQ::Il;;lIIIII;l;iQCJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCJJCLi;!lIIIIIIIIII,l[1]i,:l!::IlIIIIIIIlI,:lIlIIIIIIl;]CXn);,IIlI,cv,l;llIIl,{ZJCUJCCJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCJJLX::IIIIIIIIIIIl;,::;l!I^QQ,l;IIIIII;IllII:IIIIIIII;;;":IllI:~YQ0{,lIIIIIl,(ZJUCJUJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCJU0XI:llIIIIIIIIIIlll!l::tZCIllIIIIIIl!I;!,1lIIIIIIll;Illll""(LLJJO-:lIIIIIl"}L0CJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCJCCJC0J],;IllIIIIIIl!II:"?U0Y0n";lIIIIIIIl;,)w?;iIIIIIIlllI:,-XOJUJUJL],llIIIll"ljLOLUUJCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCJCCUCZn-:,:;IIIllI;,:_xOCUCUQxI,;IIllI,:lfOLJl,IIlII;;:,:]uOQUJJJCUC0|,:IlIIlII,l(cLOLJCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCJCCCJJ0OX/]i;::,,;i{c0QUUJJJJ0C/_I:,";~QC0JCLC}I,,":Ii}fYOQJJCCCCCCJJOz-,::Illl!;,,!]vQJJJCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJCL00LJYcvvYCOQJUJJJJJCJJQQUcuvXLQJUJLUJOLzvczUQZQLJJCCJCJJCCCCJLOz1i,,,,;Ill;,,/LJJCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJJUUJJCCCLQLLQ00OOOO00O0Q0OOOZOQQQLLQLCJCLLLLJUYYUUUJJJJJCJJJJJUUL0CXr|~Il;Il!;~OCJCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJCCLQ0QCzujQ({[]]][[[}{{1))|tfjxuvzXJCCLLQ000O0000QLLLLCLLLCCCCLCQOOO];l;III,|QUJCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCJJCCJC00Ccf[~I,",,:::::::,::,",::,,,,,,":;;;li~+_?[{)QfjrnvzXXYYUJJJJUXut?,:l;Ill;iLJJCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCJJCJULOLx{!",:;IIllllllllllllllllllllllllIIIIII;;;::::,,,,,,"",,:;IllII;:,,,IIIIIl;:YLUCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCJCJJULOz1l",;lllIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIlllIIIIIlllllIIIIIIIII;;Il!llIIIII;:vQUJCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCUCOz[:,IllIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIl:!X0CJJCJCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCJOL{,:IlIIlIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIl;"?CQULQ0CUCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCJCCJOnI,ll;IlIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIlIll;,ljOCULcjrYLJCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCJCJCJ0(";I;I;IIIIIIIIlll!!l!llllllllllllllIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIlIIlI:,lQLOJJQztxn/JCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCULCO},l;;IllIllII;;;;;;::::::::::::;;;:;;;;IIIlllllllllllllIIIIIIIIIllIIIllI;:::_jL0CUJCLrX)tcxQJJJCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCJUO("ll!l;;:,,,:;li+_-][[[[[[]]?-__+i!!lI;;:::,,,,,,:::::;;IIIIIIIIIII;;:,,,I]tXQQLCUJCCCrcQxYxQJJJCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCJQn"lII,"Ii[|juXUJL000000000Q0QQQ000QLLCJUYXzvunrfQ()}[-_~i!ll;;;;;;;Ii_[)jzL0QLJJJJJCJJLX(Un(CCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCJCLLi,,,i1xYLOOQLLLCCJJJJUUJJJJJJJJJJCCJCCCLCLLLQLQQ0000000QLLCCJUUUYUJCLL00QQCJJJCJJCJCJCJLYfrCLJCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCJCJ-l)cLO0LCJJJJJJCCCCCCCCCCCCCCCCCCCCCCCCJJJJJJJJJJJJJJJJJCCCCCLCCLCCCCCJJJJCCCCCCCCCCCCCJLQQLJCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCUCQLZQJUUJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJJJJJJJCJJJCCCCCCCCCCCCCCCCCCCJJJJCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCJCCJJUCLCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJJCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCJCJCCCJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJJCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC']

cal = list(zip(*cal[::-1]))
# a = Turtle()
# b = Turtle()

bgcolor('gold')
# color = {'c':}
col=len(cal[0])
row =len(cal)
x = -300
y = 200
penup()
shape("circle")
# a.shape("circle")
# b.shape("circle")
turtlesize(0.3,0.3,1)
# a.turtlesize(0.1,0.1,1)
goto(x,y)
pixelx = 4
pixely = 4
penup()
# a.penup()
speed(0)
for c in range(col-1, 0, -1):
    for r in range(0, row, 1):
        # print(r,c)
        if cal[r][c] == "C":
            continue
        else:
            color('navy')
        
        goto(r*pixelx-300,c*pixely-100)
        # a.goto(r*pixelx-302,c*pixely-100)
        # a.stamp()
        stamp()

done()