import turtle

# Create the turtle window
window = turtle.Screen()
turtle.bgcolor("skyblue")
turtle.color("black", "green")
turtle.begin_fill()

# Create the arrow turtle
arrow = turtle.Turtle()
arrow.speed(1)

# Draw the arrow shape
soban = "Programmer"
if soban == "Programmer":
    arrow.forward(75)
    arrow.right(90)
    arrow.forward(10)
    arrow.right(90)
    arrow.forward(15)
    arrow.left(90)
    arrow.forward(5)
    arrow.left(90)
    arrow.forward(35)
    arrow.left(90)
    arrow.forward(5)
    arrow.left(90)
    arrow.forward(15)
    arrow.right(90)
    arrow.forward(10)
    arrow.right(90)
    arrow.forward(75)
    arrow.left(90)
    arrow.forward(60)
    arrow.left(90)
    arrow.forward(155)
    arrow.left(90)
    arrow.forward(60)
    arrow.left(90)
    arrow.penup()
    arrow.forward(180)
    arrow.right(90)
    arrow.forward(15)
    arrow.left(90)
    arrow.pendown()
    arrow.forward(50)
    arrow.left(90)
    arrow.forward(110)
    arrow.left(90)
    arrow.forward(50)
    arrow.left(90)
    arrow.forward(110)
    arrow.right(180)
    arrow.penup()
    arrow.forward(30)
    arrow.right(90)
    arrow.forward(5)
    arrow.pendown()
    arrow.forward(20)
    arrow.left(90)
    arrow.forward(4)
    arrow.left(90)
    arrow.forward(20)
    arrow.left(90)
    arrow.forward(4)
    arrow.left(180)
    arrow.forward(8)
    arrow.right(90)
    arrow.forward(20)
    arrow.right(90)
    arrow.forward(4)
    arrow.right(90)
    arrow.forward(10)
    arrow.right(90)
    arrow.penup()
    arrow.forward(40)
    arrow.pendown()
    arrow.circle(2)
    arrow.right(180)
    arrow.penup()
    arrow.forward(150)
    arrow.right(90)
    arrow.forward(40)
    arrow.pendown()
    arrow.forward(15)
    arrow.right(90)
    arrow.forward(17)
    arrow.right(45)
    arrow.forward(6)
    arrow.right(45)
    arrow.forward(9)
    arrow.right(45)
    arrow.forward(6)
    arrow.right(45)
    arrow.forward(17)
    arrow.right(90)
    arrow.penup()
    arrow.forward(7.5)
    arrow.right(90)
    arrow.pendown()
    arrow.forward(20)
    arrow.right(180)
    arrow.forward(4)
    arrow.right(90)
    arrow.forward(8)
    arrow.right(180)
    arrow.forward(15)
    arrow.penup()
    arrow.right(90)
    arrow.forward(17)
    arrow.right(90)
    arrow.forward(80)
    arrow.pendown()
    arrow.forward(80)
    arrow.right(90)
    arrow.forward(30)
    arrow.right(90)
    arrow.forward(80)
    arrow.right(90)
    arrow.forward(30)
    arrow.right(90)
    arrow.forward(8)
    arrow.right(90)
    arrow.forward(5)
    arrow.right(90)
    arrow.forward(5)
    arrow.right(90)
    arrow.forward(5)
    arrow.right(90)
    arrow.forward(16)

turtle.done()
